apiVersion: v1
kind: Service
metadata:
  name: salesnest-web
  labels:
    app: salesnest-web
spec:
  type: LoadBalancer
  selector:
    app: salesnest-web
  ports:
    - name: http
      port: 5000
      targetPort: 5000
